### PR TITLE
Update to Phaser 3.60 and fix related bugs

### PR DESCRIPTION
**Pull request by sky-is-winning**
This commit updates Phaser to v3.60.0

Also:
- updated phasereditor2d-launcher to version 3.61.0, for full Phaser 3.60.0 support
- changed the NineSlice component to use the PhaserEditor2D NinePatchContainer, as updating Phaser broke the component.
- changed any references from `Phaser.Tweens.Tween.remove()` to `Phaser.Tweens.TweenManager.remove(Phaser.Tweens.Tween)` as the former does not work with the overhauled tween manager.
- changed the relative positioning of saved penguin cards from `BOTTOM_RIGHT` to `CENTER` to fix them being misaligned.
- made the SnowballFactory set a snowball's Y position on the end of the tween, as the overhauled tween manager does not send the update event on the last frame of a tween anymore.

### CODE REVIEW

**Comment by HinataNekoNya** [comment]
There is a conflict in the pull if you do not correct it the code will never be able to be pulled I advise you to check with the developer on Discord 😅

**Comment by sky-is-winning** [comment]
> There is a conflict in the pull if you do not correct it the code will never be able to be pulled I advise you to check with the developer on Discord 😅

@HinataNekoNya Hello. I am in communication with the developer and talk to them frequently. It is not necessarily my responsibility to resolve these conflicts, as there were none when I originally made the pull request. 
I will resolve them anyway.

**Comment by HinataNekoNya** [comment]
Okay In any case I really like your work and I can't wait to see all its updates initialized !

**Comment by sky-is-winning** [comment]
Addressed in 8e363d5abda8cc2aefeb0f7da77df2eb8127601e

**Pull request closed without merging**
